apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-mainui
spec:
  replicas: 2
  selector:
    matchLabels:
      name: apache
      app: main
      rel: stable
  template:
    metadata:
      name: aaa
      labels:
        name: apache
        app: main
        rel: stable
    spec:
      containers:
        - name: http:2.2
          image: http:2.2


